### ISSUE TITLE
SSH Remote still not working!

### ISSUE THREAD

**Issue by stepharo** [cursor/cursor#1179]
[Error  - 21:33:48.455] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:871338)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438343
	
	
	
	I have this our since months between two macs in a local network. SSH via Cursor Terminal: no problem. 
	
	I also tried the link, where it fetches and there is no correct file under the url...
	
	
<img width="1187" alt="Bildschirmfoto 2024-01-15 um 23 00 44" src="https://github.com/getcursor/cursor/assets/32849830/8c6a2304-eb65-458d-854b-a883ae18e1ce">

**Comment by stepharo** [comment]
will here anybody answer?

**Comment by stepharo** [comment]
please den me the current urls for intel and m1 macs

**Comment by comatose-tortoise** [comment]
I'm also getting Error resolving authority when trying to connect to a remote SSH server which is running on Windows.

**Comment by ChaostixZix** [comment]
I'm also getting this error

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
