### ISSUE TITLE
start cursor errror : version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Hippop** [cursor/cursor#1828]
System :Red Hat 8.3.1-4
system glibc:2.28
Error:
 [main 2024-09-05T10:54:30.379Z] [uncaught exception in main]: Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorjVMvha/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2024-09-05T10:54:30.379Z] Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorjVMvha/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at R (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_cursorjVMvha/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at f._compile (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:1260)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at R (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_cursorjVMvha/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at f._compile (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:1260)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at a (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:98)
    at l.load (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:1640)
    at s.load (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:4:13734)
    at f (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:9338)
    at Object.errorback (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:9457)
    at s.triggerErrorback (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:4:14028)
    at /tmp/.mount_cursorjVMvha/resources/app/out/main.js:4:13779
    at l.load (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:5:1657)
    at s.load (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:4:13734)
    at f (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:9338)
    at V._loadModule (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:9466)
    at V._resolve (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:7:452)
    at V.defineModule (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:5561)
    at V._relativeRequire (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:6185)
    at e (/tmp/.mount_cursorjVMvha/resources/app/out/main.js:6:8516)
    at /tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:50:32550
    at new Promise (<anonymous>)
    at /tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:50:32530
    at new Promise (<anonymous>)
    at b.p (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:50:32510)
    at b.n (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:50:32062)
    at new b (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:50:29522)
    at t (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:114:87211)
    at /tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:114:85143
    at t.init (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:114:85473)
    at E.value (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:116:30762)
    at i.B (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:41:739)
    at i.C (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:41:811)
    at i.fire (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:41:1027)
    at E.value (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:116:23160)
    at i.B (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:41:739)
    at i.fire (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:41:958)
    at K.load (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:116:129136)
    at he.rb (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:117:47909)
    at async he.qb (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:117:47214)
    at async he.Y (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:117:33060)
    at async he.open (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:117:29211)
    at async vt.startup (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:117:59077)
    at async ve.a (/tmp/.mount_cursorjVMvha/resources/app/out/vs/code/electron-main/main.js:119:1272)

i dont want to upgrade my glibc, how can i use cursor?
thanks for sharing

**Comment by nuomizai** [comment]
I met the same error on my ubuntu 18.04, and I didn't install a VSCode.

**Comment by DWDuq** [comment]
@nuomizai Same. I'm also on 18.04 and it appears our older version of Linux has too old a version of glibc.  Unfortunately it seems like updating to 2.29 without upgrading to a newer version of the OS is risky and not recommended.

I wonder if there's an older version of Cursor that uses an older version go glibc that I can download?

**Comment by nuomizai** [comment]
> @nuomizai Same. I'm also on 18.04 and it appears our older version of Linux has too old a version of glibc. Unfortunately it seems like updating to 2.29 without upgrading to a newer version of the OS is risky and not recommended.
> 
> I wonder if there's an older version of Cursor that uses an older version go glibc that I can download?

Indeed, that's correct. But I couldn't locate an older version of Cursor. It seems using an upgraded system version might be the best solution.

**Comment by leerob** [comment]
Thanks for reaching out! For billing, payment, and subscription questions, please email us directly at **hi@cursor.com** - our team can help you much faster there since they have access to your account information.

We're closing this issue, but please don't hesitate to email us.
