### ISSUE TITLE
can not open dev container, `Failed to download VS Code Server`

### ISSUE THREAD

**Issue by jiangying000** [cursor/cursor#2467]
[2024-12-09T13:32:21.979Z] Stop (658 ms): Run in container: apk info | grep -e '^libstdc++$' || (apk update && apk add libstdc++)
[2024-12-09T13:32:22.387Z] Failed to download VS Code Server (https://cursor.blob.core.windows.net/remote-releases/a846435528b4b760494a836f96f0739889253530/vscode-reh-linux-alpine.tar.gz): HTTP 404 - The specified blob does not exist.
[2024-12-09T13:32:22.387Z] Retrying to download VS Code Server.
[2024-12-09T13:32:22.644Z] Stop (1316 ms): Downloading VS Code Server
[2024-12-09T13:32:22.647Z] Error: Server returned 404
    at f (vscode-file://vscode-app/c:/Users/5/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:1212:49047)
    at C.download (vscode-file://vscode-app/c:/Users/5/AppData/Local/Programs/cursor/resources/app/out/vs/workbench/workbench.desktop.main.js:1213:1915)

**Comment by Elijas** [comment]
same here
possible duplicate https://github.com/getcursor/cursor/issues/2359

**Comment by Elijas** [comment]
SSH to windows is not currently supported. You can try connecting to WSL instead.

_Originally posted by @tmm1 in https://github.com/getcursor/cursor/issues/2251#issuecomment-2406409866_

**Comment by tmm1** [comment]
Does it work with non-alpine container?

**Comment by nigiwen** [comment]
Problems unique to alpine container

**Comment by leerob** [comment]
Thanks for opening this issue! We've moved our community support to the [Cursor Forum](https://forum.cursor.com) where you can get help from both the team and other users.

If this is a specific bug that you can still reproduce, please open a new issue with clear reproduction steps on the forum.

Thanks you!
