### ISSUE TITLE
Is it possible to use a cursor tab in an overleaf workshop?

### ISSUE THREAD

**Issue by polar1shu** [cursor/cursor#2495]
I want to use cursor tab in overleaf workshop but I found that he doesn't work. I would like to know if this is normal?

**Comment by JohnDoe2025-ai** [comment]
In Overleaf, a "cursor tab" is not a specific feature, but it sounds like you're referring to some functionality related to moving or positioning the cursor across different sections of your document, or using tabbing for organizing your workflow in the editor.

While Overleaf does not have a "cursor tab" feature in the sense of multiple independent tabs for cursor positioning, here are a few related ways you can manage your workflow and document editing efficiently:

1. **Multiple Editors or Split View**:
   Overleaf allows you to use a split view where you can see different parts of your document side-by-side. This can help if you need to refer to one section of the document while editing another.
   - To activate split view, click the **"Split"** icon in the top-right corner of the editor.

2. **Multiple Documents in a Project**:
   If your workshop involves working with multiple documents (e.g., chapters, appendices, or separate files), Overleaf supports multiple files within a single project. You can navigate between them using the file tree on the left side. However, you can only view one file at a time in the editor window.

3. **Keyboard Shortcuts**:
   Overleaf supports various keyboard shortcuts, which may help you quickly move your cursor and navigate between parts of your document. For example:
   - **Ctrl + G (Cmd + G on macOS)** allows you to search for a specific part of your document.
   - **Ctrl + F (Cmd + F on macOS)** to find text within the current document.
   - **Ctrl + [ or ]** to navigate between sections in your document (e.g., move to the previous or next section).

4. **Tabs for Files**:
   Overleaf does have tabs for different open files, but these are for different files in your project, not for managing different cursor locations within the same file. You can open multiple files in separate tabs, but switching between them is more of a file navigation feature.

If you're referring to a specific Overleaf feature, like a cursor management tool, please clarify, and I can provide more details!

**Comment by polar1shu** [comment]
I want to use the overleaf workshop plugin in cursor for essay writing. cursor has a great advantage of auto-completion, i.e. write some word and it predicts the next word or sentence. But I am not able to use this feature in overleaf workshop, but I can use the complementation feature in the local file. I don't know if this is the reason for overleaf workshop.

**Comment by hilookas** [comment]
In `cursor indexing & retrieval panel`, it shows: 

```log
2025-02-10 15:42:03.646 [error] Unhandled error in doUpdate root directory '/{***PROJECT_NAME***}' does not exist
2025-02-10 15:42:03.654 [error] TypeError: Cannot read properties of undefined (reading 'initWithRipgrepIgnore')
	at Q.initializeMerkleTreeWithRipgrepIgnore (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:203031)
	at Q.getServerStatus (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:200620)
	at async Q.startIndexingRepository (/Applications/Cursor.app/Contents/Resources/app/extensions/cursor-retrieval/dist/main.js:4:201812)
```

Is there a bug in the virtual filesystem?

**Comment by JohnDoe2025-ai** [comment]
It looks like the error you’re seeing is because the root directory for your project (`/{***PROJECT_NAME***}`) doesn’t exist — that’s the key problem here. The retrieval panel is trying to initialize indexing, but it can’t find the directory. Let’s troubleshoot step by step:  

1. **Check if the directory exists**:  
   Go to the location where your project is supposed to be and confirm the directory exists and is accessible.  

2. **Verify project path settings**:  
   Open your project settings in Cursor and confirm the root directory path is set correctly — no typos, no missing folders.

3. **Permissions check**:  
   Make sure Cursor has permission to access the directory. You can adjust folder permissions via your OS settings if needed.

4. **Restart Cursor**:  
   Close and reopen Cursor — sometimes a simple restart helps clear virtual filesystem issues.

5. **Check `.cursor` folder**:  
   If your project has a `.cursor` folder (Cursor’s metadata folder), try deleting it and restarting the app. Cursor should regenerate it when the project is reopened.

6. **Re-index the project**:  
   If Cursor supports manually refreshing indexing, trigger a re-index and see if the issue persists.

7. **Filesystem issue**:  
   If none of the above works, there might indeed be a problem with Cursor’s virtual filesystem. You could try reinstalling Cursor or updating it if a newer version is available.  

Let me know what you see after trying these! If the error persists, we can dig deeper.

**Comment by deepakn97** [comment]
This is still an issue. Can someone from the team take a look at this? Running `cursor --version` gives following output:

```
0.47.8
82ef0f61c01d079d1b7e5ab04d88499d5af500e0
arm64
```

**Comment by dolphin-in-a-coma** [comment]
Experiencing the same issue here

<img width="1552" alt="Image" src="https://github.com/user-attachments/assets/c09f0d16-2699-4459-bd45-50729516b142" />

Version: 0.47.5
VSCode Version: 1.96.2
Commit: 53d6da1322f934a1058e7569ee0847b24879d180
Date: 2025-03-14T21:41:01.221Z
Electron: 32.2.6
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.3.0

**Comment by agecspnt** [comment]
Try 0.45, works for me.
