### ISSUE TITLE
ssh to remote server doesn't work after upgrading to 0.9.1

### ISSUE THREAD

**Issue by ghbtest** [cursor/cursor#847]
1) If you can, please include a screenshot of your problem
from terminal:

> [Info  - 23:01:27.651] Resolving ssh remote authority 'ssh-remote+aws-xxx' (attemp #1)
> [Trace  - 23:01:27.676] Identity keys:
> /Users/xxx/xxx/aws/xxxx.key ssh-rsa xxx=
> [Info  - 23:01:28.381] Trying no-auth authentication
> [Info  - 23:01:28.523] Trying publickey authentication: /Users/xxx/xxx/aws/xxxx.key ssh-rsa xxx=
> [Trace  - 23:01:29.587] Server install command:
> 
> # Server installation script
> 
> TMP_DIR="${XDG_RUNTIME_DIR:-"/tmp"}"
> 
> DISTRO_VERSION="0.9.1"
> DISTRO_COMMIT="30d21e59529ff0a52d8a847c419e668f2fd2d620"
> DISTRO_QUALITY="stable"
> 
> SERVER_APP_NAME="cursor-server"
> SERVER_INITIAL_EXTENSIONS=""
> SERVER_LISTEN_FLAG="--port=0"
> SERVER_DATA_DIR="$HOME/.cursor-server"
> SERVER_DIR="$SERVER_DATA_DIR/bin/$DISTRO_VERSION-$DISTRO_COMMIT"
> SERVER_SCRIPT="$SERVER_DIR/bin/$SERVER_APP_NAME"
> SERVER_LOGFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.log"
> SERVER_PIDFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.pid"
> SERVER_TOKENFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.token"
> SERVER_OS=
> SERVER_ARCH=
> SERVER_CONNECTION_TOKEN=
> SERVER_DOWNLOAD_URL=
> 
> LISTENING_ON=
> OS_RELEASE_ID=
> ARCH=
> PLATFORM=
> 
> # Mimic output from logs of remote-ssh extension
> print_install_results_and_exit() {
>     echo "23fe639f014cab9ef55d1139: start"
>     echo "exitCode==$1=="
>     echo "listeningOn==$LISTENING_ON=="
>     echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
>     echo "logFile==$SERVER_LOGFILE=="
>     echo "osReleaseId==$OS_RELEASE_ID=="
>     echo "arch==$ARCH=="
>     echo "platform==$PLATFORM=="
>     echo "tmpDir==$TMP_DIR=="
>     
>     echo "23fe639f014cab9ef55d1139: end"
>     exit 0
> }
> 
> # Check if platform is supported
> PLATFORM="$(uname -s)"
> case $PLATFORM in
>     Darwin)
>         SERVER_OS="darwin"
>         ;;
>     Linux)
>         SERVER_OS="linux"
>         ;;
>     FreeBSD)
>         SERVER_OS="freebsd"
>         ;;
>     DragonFly)
>         SERVER_OS="dragonfly"
>         ;;
>     *)
>         echo "Error platform not supported: $PLATFORM"
>         print_install_results_and_exit 1
>         ;;
> esac
> 
> # Check machine architecture
> ARCH="$(uname -m)"
> case $ARCH in
>     x86_64 | amd64)
>         SERVER_ARCH="x64"
>         ;;
>     armv7l | armv8l)
>         SERVER_ARCH="armhf"
>         ;;
>     arm64 | aarch64)
>         SERVER_ARCH="arm64"
>         ;;
>     ppc64le)
>         SERVER_ARCH="ppc64le"
>         ;;
>     *)
>         echo "Error architecture not supported: $ARCH"
>         print_install_results_and_exit 1
>         ;;
> esac
> 
> # https://www.freedesktop.org/software/systemd/man/os-release.html
> OS_RELEASE_ID="$(grep -i '^ID=' /etc/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
> if [[ -z $OS_RELEASE_ID ]]; then
>     OS_RELEASE_ID="$(grep -i '^ID=' /usr/lib/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
>     if [[ -z $OS_RELEASE_ID ]]; then
>         OS_RELEASE_ID="unknown"
>     fi
> fi
> 
> # Create installation folder
> if [[ ! -d $SERVER_DIR ]]; then
>     mkdir -p $SERVER_DIR
>     if (( $? > 0 )); then
>         echo "Error creating server install directory"
>         print_install_results_and_exit 1
>     fi
> fi
> 
> SERVER_DOWNLOAD_URL="$(echo "https://cursor.blob.core.windows.net/remote-releases/\${version}-\${commit}/vscode-reh-\${os}-\${arch}.tar.gz" | sed "s/\${quality}/$DISTRO_QUALITY/g" | sed "s/\${version}/$DISTRO_VERSION/g" | sed "s/\${commit}/$DISTRO_COMMIT/g" | sed "s/\${os}/$SERVER_OS/g" | sed "s/\${arch}/$SERVER_ARCH/g")"
> 
> echo "Downloading server from '$SERVER_DOWNLOAD_URL'"
> 
> # Check if server script is already installed
> if [[ ! -f $SERVER_SCRIPT ]]; then
>     if [[ "$SERVER_OS" = "dragonfly" ]] || [[ "$SERVER_OS" = "freebsd" ]]; then
>         echo "Error "$SERVER_OS" needs manual installation of remote extension host"
>         print_install_results_and_exit 1
>     fi
> 
>     pushd $SERVER_DIR > /dev/null
> 
>     if [[ ! -z $(which wget) ]]; then
>         wget --tries=3 --timeout=10 --continue --no-verbose -O vscode-server.tar.gz $SERVER_DOWNLOAD_URL
>     elif [[ ! -z $(which curl) ]]; then
>         curl --retry 3 --connect-timeout 10 --location --show-error --silent --output vscode-server.tar.gz $SERVER_DOWNLOAD_URL
>     else
>         echo "Error no tool to download server binary"
>         print_install_results_and_exit 1
>     fi
> 
>     if (( $? > 0 )); then
>         echo "Error downloading server from $SERVER_DOWNLOAD_URL"
>         print_install_results_and_exit 1
>     fi
> 
>     tar -xf vscode-server.tar.gz --strip-components 1
>     if (( $? > 0 )); then
>         echo "Error while extracting server contents"
>         print_install_results_and_exit 1
>     fi
> 
>     if [[ ! -f $SERVER_SCRIPT ]]; then
>         echo "Error server contents are corrupted"
>         print_install_results_and_exit 1
>     fi
> 
>     rm -f vscode-server.tar.gz
> 
>     popd > /dev/null
> else
>     echo "Server script already installed in $SERVER_SCRIPT"
> fi
> 
> # Try to find if server is already running
> if [[ -f $SERVER_PIDFILE ]]; then
>     SERVER_PID="$(cat $SERVER_PIDFILE)"
>     echo "Server PID: $SERVER_PID"
>     echo "Server script: $SERVER_SCRIPT"
>     SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
> else
>     echo "Server script: $SERVER_SCRIPT"
>     SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
> fi
> 
> echo "Server running process: $SERVER_RUNNING_PROCESS"
> 
> if [[ -z $SERVER_RUNNING_PROCESS ]]; then
>     if [[ -f $SERVER_LOGFILE ]]; then
>         rm $SERVER_LOGFILE
>     fi
>     if [[ -f $SERVER_TOKENFILE ]]; then
>         rm $SERVER_TOKENFILE
>     fi
> 
>     touch $SERVER_TOKENFILE
>     chmod 600 $SERVER_TOKENFILE
>     SERVER_CONNECTION_TOKEN="74e66d6a-b8aa-43dc-8456-00fee5cc9225"
>     echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE
> 
>     $SERVER_SCRIPT --start-server --host=127.0.0.1 $SERVER_LISTEN_FLAG $SERVER_INITIAL_EXTENSIONS --connection-token-file $SERVER_TOKENFILE --telemetry-level off --enable-remote-auto-shutdown --accept-server-license-terms &> $SERVER_LOGFILE &
>     echo $! > $SERVER_PIDFILE
> else
>     echo "Server script is already running $SERVER_SCRIPT"
> fi
> 
> if [[ -f $SERVER_TOKENFILE ]]; then
>     SERVER_CONNECTION_TOKEN="$(cat $SERVER_TOKENFILE)"
> else
>     echo "Error server token file not found $SERVER_TOKENFILE"
>     print_install_results_and_exit 1
> fi
> 
> if [[ -f $SERVER_PIDFILE ]]; then
>     SERVER_PID="$(cat $SERVER_PIDFILE)"
>     SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
> else
>     SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
> fi
> if [[ -f $SERVER_LOGFILE ]]; then
>     for i in {1..5}; do
>         LISTENING_ON="$(cat $SERVER_LOGFILE | grep -E 'Extension host agent listening on .+' | sed 's/Extension host agent listening on //')"
>         if [[ -n $LISTENING_ON ]]; then
>             break
>         fi
>         sleep 0.5
>     done
> 
>     if [[ -z $LISTENING_ON ]]; then
>         echo "Error server did not start sucessfully"
>         print_install_results_and_exit 1
>     fi
> else
>     echo "Error server log file not found $SERVER_LOGFILE"
>     print_install_results_and_exit 1
> fi
> 
> # Finish server setup
> print_install_results_and_exit 0
> 
> [Trace  - 23:01:30.864] Server install command stderr:
> 
> gzip: stdin: invalid compressed data--format violated
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
> 
> [Trace  - 23:01:30.864] Server install command stdout:
> Downloading server from 'https://cursor.blob.core.windows.net/remote-releases/0.9.1-30d21e59529ff0a52d8a847c419e668f2fd2d620/vscode-reh-linux-x64.tar.gz'
> Error while extracting server contents
> 23fe639f014cab9ef55d1139: start
> exitCode==1==
> listeningOn====
> connectionToken====
> logFile==/home/ubuntu/.cursor-server/.30d21e59529ff0a52d8a847c419e668f2fd2d620.log==
> osReleaseId==ubuntu==
> arch==x86_64==
> platform==Linux==
> tmpDir==/run/user/1000==
> 23fe639f014cab9ef55d1139: end
> 
> [Error  - 23:01:30.865] Error resolving authority
> Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
> 	at t.installCodeServer (/Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:763232)
> 	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> 	at async /Applications/Cursor.app/Contents/Resources/app/extensions/open-remote-ssh/dist/main.js:1:438101

2) Please include the name of your operating system
macOS Monterey

3) If you can, steps to reproduce are super helpful
connect to an aws instance using ssh command: Connect to Host -> select a host -> error message "could not establish connection to "host xxx"

**Comment by Sanger2000** [comment]
Try deleting ~/.cursor-server on the remote host (with rm -rf), then re-connecting. This is a known bug where when downloading remote-ssh, it very rarely downloads a corrupted version. We plan on fixing this in the next release

**Comment by binhna** [comment]
> Try deleting ~/.cursor-server on the remote host (with rm -rf), then re-connecting. This is a known bug where when downloading remote-ssh, it very rarely downloads a corrupted version. We plan on fixing this in the next release

This works for me, thank you

**Comment by ghbtest** [comment]
seems like need to do this repeatedly - it worked once, then after 1 or 2 days the same problem occurred again, so tried deleting the folder again and it worked again.

**Comment by SunSeaLucky** [comment]
> Try deleting ~/.cursor-server on the remote host (with rm -rf), then re-connecting. This is a known bug where when downloading remote-ssh, it very rarely downloads a corrupted version. We plan on fixing this in the next release

Or sth like `.codeium/` may work

**Comment by TheLexoPlexx** [comment]
This never worked for me but I created a symlink from `.cursor-server/extensions` to `.vscode-server/extensions` and that did the trick for now.
