### ISSUE TITLE
Missing GLIBC_2.29 on Ubuntu 18

### ISSUE THREAD

**Issue by mmathew23** [cursor/cursor#879]
When executing the AppImage on Ubuntu 18.04 the IDE launches, but is reporting many errors due to missing GLIBC_2.29.

[main 2023-09-06T05:10:02.954Z] [storage state.vscdb] open(): Unable to open DB due to Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2023-09-06T05:10:02.969Z] update#ctor - updates are disabled as there is no update URL
[main 2023-09-06T05:10:03.054Z] [storage state.vscdb] open(): Unable to open DB due to Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2023-09-06T05:10:03.055Z] [storage state.vscdb] open(): Unable to use backup due to Error: ENOENT: no such file or directory, unlink '/home/mathew/.config/Cursor/User/globalStorage/state.vscdb'
[main 2023-09-06T05:10:03.055Z] [storage main] initialize(): Unable to init storage due to Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2023-09-06T05:10:03.059Z] [storage state.vscdb] open(): Unable to use backup due to Error: ENOENT: no such file or directory, unlink '/home/mathew/.config/Cursor/User/workspaceStorage/366f5cfa7db63a969a5505965da913b4/state.vscdb'
[main 2023-09-06T05:10:03.059Z] [storage main] initialize(): Unable to init storage due to Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2023-09-06T05:10:03.159Z] [uncaught exception in main]: Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2023-09-06T05:10:03.160Z] Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at P (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at l._compile (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at P (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_cursorsOQc9n/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at l._compile (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:98)
    at n.load (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:1637)
    at f.load (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:4:13573)
    at l (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:9301)
    at Object.errorback (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:9420)
    at f.triggerErrorback (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:4:13867)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/main.js:4:13618
    at n.load (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:5:1654)
    at f.load (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:4:13573)
    at l (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:9301)
    at h._loadModule (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:9429)
    at h._resolve (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:7:452)
    at h.defineModule (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:5524)
    at h._relativeRequire (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:6148)
    at e (/tmp/.mount_cursorsOQc9n/resources/app/out/main.js:6:8479)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:26:32502
    at new Promise (<anonymous>)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:26:32482
    at new Promise (<anonymous>)
    at P.p (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:26:32462)
    at P.n (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:26:32013)
    at new P (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:26:29709)
    at E.r (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:87:95671)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:87:93619
    at E.init (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:87:93975)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:89:29997
    at p.invoke (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:145)
    at a.deliver (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:2121)
    at s.fire (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:1729)
    at /tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:89:22718
    at p.invoke (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:145)
    at a.deliver (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:2121)
    at s.fire (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:19:1729)
    at bt.load (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:89:108085)
    at at.ib (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:90:46337)
    at async at.hb (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:90:45554)
    at async at.N (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:90:31863)
    at async at.open (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:90:27875)
    at async e.CodeApplication.startup (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:90:55971)
    at async Ae.a (/tmp/.mount_cursorsOQc9n/resources/app/out/vs/code/electron-main/main.js:92:1266)

**Comment by mmathew23** [comment]
Maybe the right question is if Ubuntu 18 is supported?

**Comment by lishuaiyin02** [comment]
解决了吗？18.04我也遇到这个问题了
